// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: luckyagent.proto

package luckyagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LuckyAgentService_Chat_FullMethodName                = "/luckyagent.LuckyAgentService/Chat"
	LuckyAgentService_ChatStream_FullMethodName          = "/luckyagent.LuckyAgentService/ChatStream"
	LuckyAgentService_MemoryStore_FullMethodName         = "/luckyagent.LuckyAgentService/MemoryStore"
	LuckyAgentService_MemoryRecall_FullMethodName        = "/luckyagent.LuckyAgentService/MemoryRecall"
	LuckyAgentService_MemoryList_FullMethodName          = "/luckyagent.LuckyAgentService/MemoryList"
	LuckyAgentService_MemoryDelete_FullMethodName        = "/luckyagent.LuckyAgentService/MemoryDelete"
	LuckyAgentService_RAGIndex_FullMethodName            = "/luckyagent.LuckyAgentService/RAGIndex"
	LuckyAgentService_RAGSearch_FullMethodName           = "/luckyagent.LuckyAgentService/RAGSearch"
	LuckyAgentService_WorkflowCreate_FullMethodName      = "/luckyagent.LuckyAgentService/WorkflowCreate"
	LuckyAgentService_WorkflowGet_FullMethodName         = "/luckyagent.LuckyAgentService/WorkflowGet"
	LuckyAgentService_WorkflowList_FullMethodName        = "/luckyagent.LuckyAgentService/WorkflowList"
	LuckyAgentService_WorkflowDelete_FullMethodName      = "/luckyagent.LuckyAgentService/WorkflowDelete"
	LuckyAgentService_WorkflowStart_FullMethodName       = "/luckyagent.LuckyAgentService/WorkflowStart"
	LuckyAgentService_WorkflowInstanceGet_FullMethodName = "/luckyagent.LuckyAgentService/WorkflowInstanceGet"
	LuckyAgentService_HealthCheck_FullMethodName         = "/luckyagent.LuckyAgentService/HealthCheck"
)

// LuckyAgentServiceClient is the client API for LuckyAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LuckyAgent gRPC Service
type LuckyAgentServiceClient interface {
	// Chat
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
	// Memory
	MemoryStore(ctx context.Context, in *MemoryStoreRequest, opts ...grpc.CallOption) (*MemoryEntry, error)
	MemoryRecall(ctx context.Context, in *MemoryRecallRequest, opts ...grpc.CallOption) (*MemoryRecallResponse, error)
	MemoryList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MemoryListResponse, error)
	MemoryDelete(ctx context.Context, in *MemoryDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RAG
	RAGIndex(ctx context.Context, in *RAGIndexRequest, opts ...grpc.CallOption) (*RAGIndexResponse, error)
	RAGSearch(ctx context.Context, in *RAGSearchRequest, opts ...grpc.CallOption) (*RAGSearchResponse, error)
	// Workflow
	WorkflowCreate(ctx context.Context, in *WorkflowCreateRequest, opts ...grpc.CallOption) (*Workflow, error)
	WorkflowGet(ctx context.Context, in *WorkflowGetRequest, opts ...grpc.CallOption) (*Workflow, error)
	WorkflowList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkflowListResponse, error)
	WorkflowDelete(ctx context.Context, in *WorkflowDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WorkflowStart(ctx context.Context, in *WorkflowStartRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	WorkflowInstanceGet(ctx context.Context, in *WorkflowInstanceGetRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	// Health
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type luckyAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLuckyAgentServiceClient(cc grpc.ClientConnInterface) LuckyAgentServiceClient {
	return &luckyAgentServiceClient{cc}
}

func (c *luckyAgentServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LuckyAgentService_ServiceDesc.Streams[0], LuckyAgentService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LuckyAgentService_ChatStreamClient = grpc.ServerStreamingClient[ChatChunk]

func (c *luckyAgentServiceClient) MemoryStore(ctx context.Context, in *MemoryStoreRequest, opts ...grpc.CallOption) (*MemoryEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryEntry)
	err := c.cc.Invoke(ctx, LuckyAgentService_MemoryStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) MemoryRecall(ctx context.Context, in *MemoryRecallRequest, opts ...grpc.CallOption) (*MemoryRecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryRecallResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_MemoryRecall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) MemoryList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MemoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryListResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_MemoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) MemoryDelete(ctx context.Context, in *MemoryDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LuckyAgentService_MemoryDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) RAGIndex(ctx context.Context, in *RAGIndexRequest, opts ...grpc.CallOption) (*RAGIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGIndexResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_RAGIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) RAGSearch(ctx context.Context, in *RAGSearchRequest, opts ...grpc.CallOption) (*RAGSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGSearchResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_RAGSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) WorkflowCreate(ctx context.Context, in *WorkflowCreateRequest, opts ...grpc.CallOption) (*Workflow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workflow)
	err := c.cc.Invoke(ctx, LuckyAgentService_WorkflowCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) WorkflowGet(ctx context.Context, in *WorkflowGetRequest, opts ...grpc.CallOption) (*Workflow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workflow)
	err := c.cc.Invoke(ctx, LuckyAgentService_WorkflowGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) WorkflowList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkflowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowListResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_WorkflowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) WorkflowDelete(ctx context.Context, in *WorkflowDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LuckyAgentService_WorkflowDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) WorkflowStart(ctx context.Context, in *WorkflowStartRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, LuckyAgentService_WorkflowStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) WorkflowInstanceGet(ctx context.Context, in *WorkflowInstanceGetRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, LuckyAgentService_WorkflowInstanceGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyAgentServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, LuckyAgentService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LuckyAgentServiceServer is the server API for LuckyAgentService service.
// All implementations must embed UnimplementedLuckyAgentServiceServer
// for forward compatibility.
//
// LuckyAgent gRPC Service
type LuckyAgentServiceServer interface {
	// Chat
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error
	// Memory
	MemoryStore(context.Context, *MemoryStoreRequest) (*MemoryEntry, error)
	MemoryRecall(context.Context, *MemoryRecallRequest) (*MemoryRecallResponse, error)
	MemoryList(context.Context, *emptypb.Empty) (*MemoryListResponse, error)
	MemoryDelete(context.Context, *MemoryDeleteRequest) (*emptypb.Empty, error)
	// RAG
	RAGIndex(context.Context, *RAGIndexRequest) (*RAGIndexResponse, error)
	RAGSearch(context.Context, *RAGSearchRequest) (*RAGSearchResponse, error)
	// Workflow
	WorkflowCreate(context.Context, *WorkflowCreateRequest) (*Workflow, error)
	WorkflowGet(context.Context, *WorkflowGetRequest) (*Workflow, error)
	WorkflowList(context.Context, *emptypb.Empty) (*WorkflowListResponse, error)
	WorkflowDelete(context.Context, *WorkflowDeleteRequest) (*emptypb.Empty, error)
	WorkflowStart(context.Context, *WorkflowStartRequest) (*WorkflowInstance, error)
	WorkflowInstanceGet(context.Context, *WorkflowInstanceGetRequest) (*WorkflowInstance, error)
	// Health
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedLuckyAgentServiceServer()
}

// UnimplementedLuckyAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLuckyAgentServiceServer struct{}

func (UnimplementedLuckyAgentServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLuckyAgentServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedLuckyAgentServiceServer) MemoryStore(context.Context, *MemoryStoreRequest) (*MemoryEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryStore not implemented")
}
func (UnimplementedLuckyAgentServiceServer) MemoryRecall(context.Context, *MemoryRecallRequest) (*MemoryRecallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryRecall not implemented")
}
func (UnimplementedLuckyAgentServiceServer) MemoryList(context.Context, *emptypb.Empty) (*MemoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryList not implemented")
}
func (UnimplementedLuckyAgentServiceServer) MemoryDelete(context.Context, *MemoryDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryDelete not implemented")
}
func (UnimplementedLuckyAgentServiceServer) RAGIndex(context.Context, *RAGIndexRequest) (*RAGIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RAGIndex not implemented")
}
func (UnimplementedLuckyAgentServiceServer) RAGSearch(context.Context, *RAGSearchRequest) (*RAGSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RAGSearch not implemented")
}
func (UnimplementedLuckyAgentServiceServer) WorkflowCreate(context.Context, *WorkflowCreateRequest) (*Workflow, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowCreate not implemented")
}
func (UnimplementedLuckyAgentServiceServer) WorkflowGet(context.Context, *WorkflowGetRequest) (*Workflow, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowGet not implemented")
}
func (UnimplementedLuckyAgentServiceServer) WorkflowList(context.Context, *emptypb.Empty) (*WorkflowListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowList not implemented")
}
func (UnimplementedLuckyAgentServiceServer) WorkflowDelete(context.Context, *WorkflowDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowDelete not implemented")
}
func (UnimplementedLuckyAgentServiceServer) WorkflowStart(context.Context, *WorkflowStartRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowStart not implemented")
}
func (UnimplementedLuckyAgentServiceServer) WorkflowInstanceGet(context.Context, *WorkflowInstanceGetRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowInstanceGet not implemented")
}
func (UnimplementedLuckyAgentServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLuckyAgentServiceServer) mustEmbedUnimplementedLuckyAgentServiceServer() {}
func (UnimplementedLuckyAgentServiceServer) testEmbeddedByValue()                           {}

// UnsafeLuckyAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LuckyAgentServiceServer will
// result in compilation errors.
type UnsafeLuckyAgentServiceServer interface {
	mustEmbedUnimplementedLuckyAgentServiceServer()
}

func RegisterLuckyAgentServiceServer(s grpc.ServiceRegistrar, srv LuckyAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedLuckyAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LuckyAgentService_ServiceDesc, srv)
}

func _LuckyAgentService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LuckyAgentServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LuckyAgentService_ChatStreamServer = grpc.ServerStreamingServer[ChatChunk]

func _LuckyAgentService_MemoryStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).MemoryStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_MemoryStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).MemoryStore(ctx, req.(*MemoryStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_MemoryRecall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryRecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).MemoryRecall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_MemoryRecall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).MemoryRecall(ctx, req.(*MemoryRecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_MemoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).MemoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_MemoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).MemoryList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_MemoryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).MemoryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_MemoryDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).MemoryDelete(ctx, req.(*MemoryDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_RAGIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).RAGIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_RAGIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).RAGIndex(ctx, req.(*RAGIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_RAGSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).RAGSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_RAGSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).RAGSearch(ctx, req.(*RAGSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_WorkflowCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).WorkflowCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_WorkflowCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).WorkflowCreate(ctx, req.(*WorkflowCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_WorkflowGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).WorkflowGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_WorkflowGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).WorkflowGet(ctx, req.(*WorkflowGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_WorkflowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).WorkflowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_WorkflowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).WorkflowList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_WorkflowDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).WorkflowDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_WorkflowDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).WorkflowDelete(ctx, req.(*WorkflowDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_WorkflowStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).WorkflowStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_WorkflowStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).WorkflowStart(ctx, req.(*WorkflowStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_WorkflowInstanceGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowInstanceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).WorkflowInstanceGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_WorkflowInstanceGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).WorkflowInstanceGet(ctx, req.(*WorkflowInstanceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyAgentService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyAgentServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyAgentService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyAgentServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LuckyAgentService_ServiceDesc is the grpc.ServiceDesc for LuckyAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LuckyAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "luckyagent.LuckyAgentService",
	HandlerType: (*LuckyAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _LuckyAgentService_Chat_Handler,
		},
		{
			MethodName: "MemoryStore",
			Handler:    _LuckyAgentService_MemoryStore_Handler,
		},
		{
			MethodName: "MemoryRecall",
			Handler:    _LuckyAgentService_MemoryRecall_Handler,
		},
		{
			MethodName: "MemoryList",
			Handler:    _LuckyAgentService_MemoryList_Handler,
		},
		{
			MethodName: "MemoryDelete",
			Handler:    _LuckyAgentService_MemoryDelete_Handler,
		},
		{
			MethodName: "RAGIndex",
			Handler:    _LuckyAgentService_RAGIndex_Handler,
		},
		{
			MethodName: "RAGSearch",
			Handler:    _LuckyAgentService_RAGSearch_Handler,
		},
		{
			MethodName: "WorkflowCreate",
			Handler:    _LuckyAgentService_WorkflowCreate_Handler,
		},
		{
			MethodName: "WorkflowGet",
			Handler:    _LuckyAgentService_WorkflowGet_Handler,
		},
		{
			MethodName: "WorkflowList",
			Handler:    _LuckyAgentService_WorkflowList_Handler,
		},
		{
			MethodName: "WorkflowDelete",
			Handler:    _LuckyAgentService_WorkflowDelete_Handler,
		},
		{
			MethodName: "WorkflowStart",
			Handler:    _LuckyAgentService_WorkflowStart_Handler,
		},
		{
			MethodName: "WorkflowInstanceGet",
			Handler:    _LuckyAgentService_WorkflowInstanceGet_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LuckyAgentService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _LuckyAgentService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "luckyagent.proto",
}
